name: Deploy React Application

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sk485/shop-react:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push sk485/shop-react:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull sk485/shop-react:latest

      - name: Create a Docker Network
        run: docker network create app-network || true

      - name: Remove Existing Container (if any)
        run: docker rm -f reactjs-app-container || true

      - name: Run New Docker Container
        run: |
          docker run -d -p 80:80 --name reactjs-app-container \
            --network app-network \
            -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            sk485/shop-react:latest

      - name: Check React App Health
        run: |
          curl -f http://localhost || exit 1

      - name: Check Docker Container Logs
        run: docker logs reactjs-app-container
